### ISSUE TITLE
Write a benchmark to test performance between using pointers and pass by value

### ISSUE THREAD

**Issue by sbc64** [hashcloak/Meson-plugin#12]
`PostRequest` struct is passed into at least 2 layers of wrappers from `chain.go` to `proxy.go` and I'm wondering if pointers will improve performance. I need to back this up with evidence first though by writing a benchmark test.

**Comment by Mikerah** [comment]
From experience, pointers will most likely speed things up a bit and gives us the extra flexibility of being able to modify the value directly without having to do some tricks with pass-by-value. That being said, with pointers, we need to be careful in not accessing memory we don't have access to and the usual pointer caveats.

**Comment by Mikerah** [comment]
Using pointers...
