### ISSUE TITLE
Include support for Binance Chain

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/Meson-plugin#2]
As of this writing, we only support Ethereum and Ethereum-forks. Adding support for Binance Chain will enable us to eventually support Cosmos-based chains, in addition to fulfilling the fellowship requirements.

**Comment by sbc64** [comment]
This is almost done and just needs some integrations to before I close this issue. Some progress is being done here: https://github.com/hashcloak/Meson-plugin/pull/11
